# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[(0, 'Two Wheeler'), (1, 'Four Wheeler')], max_length=50)),
                ('vehicle_reg_no', models.CharField(max_length=50)),
                ('is_verified', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='vehicle_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.VehicleInformation'),
        ),
    ]
